"""Update enquiry table to autoincrement ID

Revision ID: 406cb0348473
Revises: ccbeb3b9a9f9
Create Date: 2024-07-11 01:27:26.367221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406cb0348473'
down_revision: Union[str, None] = 'ccbeb3b9a9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
