"""demo commi

Revision ID: 6accd7cad9f6
Revises: 1937555a279a
Create Date: 2024-08-09 22:12:33.311649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6accd7cad9f6'
down_revision: Union[str, None] = '1937555a279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_id', table_name='contact')
    op.drop_table('contact')
    op.drop_index('ix_enquiry_id', table_name='enquiry')
    op.drop_table('enquiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_phone', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='enquiry_pkey')
    )
    op.create_index('ix_enquiry_id', 'enquiry', ['id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    op.create_index('ix_contact_id', 'contact', ['id'], unique=False)
    # ### end Alembic commands ###
