"""creating the url table

Revision ID: d9ba3ec840d0
Revises: e2a90325a402
Create Date: 2024-08-13 20:56:36.464558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ba3ec840d0'
down_revision: Union[str, None] = 'e2a90325a402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_id'), 'url', ['id'], unique=False)
    op.create_index(op.f('ix_url_url'), 'url', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_url'), table_name='url')
    op.drop_index(op.f('ix_url_id'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
