"""enquiry removed unique key constraint

Revision ID: fb0a22f9ed82
Revises: 9b8709bae6d2
Create Date: 2024-08-02 19:30:36.122670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0a22f9ed82'
down_revision: Union[str, None] = '9b8709bae6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('enquiry_customer_name_key', 'enquiry', type_='unique')
    op.drop_constraint('enquiry_customer_phone_key', 'enquiry', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('enquiry_customer_phone_key', 'enquiry', ['customer_phone'])
    op.create_unique_constraint('enquiry_customer_name_key', 'enquiry', ['customer_name'])
    # ### end Alembic commands ###
